export const BACKGROUND_WRITER_ID = "background";
export const DEFAULT_BROWSER_ACTION_TITLE = "Privacy Containers";
export const COMMAND_ERROR_BADGE_TEXT = "!";
export const COMMAND_ERROR_BADGE_DURATION_MS = 4500;
export const PROXY_FAILOVER_TIMEOUT_SECONDS = 1; // Firefox's accepted minimum.
export const PROXY_CONNECTION_ISOLATION_PREFIX = "firefox-privacy-containers";
export const BLOCKED_PAGE_PATH = "blocked/blocked.html";
export const BLOCKED_PAGE_STORAGE_KEY = "blockedPageEntries";
export const BLOCKED_PAGE_ENTRY_TTL_MS = 5 * 60 * 1000;
export const BLOCKED_PAGE_MAX_ENTRIES = 200;
